### ISSUE TITLE
Implement virtual buttons/axes

### ISSUE THREAD

**Issue by 17cupsofcoffee** [17cupsofcoffee/tetra#100]
One feature I really miss from other frameworks is the ability to create a 'virtual' button/axis, which takes the input from multiple sources and allows them to all be queried at once. For example, you could create an virtual stick which takes input from the gamepad control stick, the arrow keys and WASD, and outputs a single `Vec2`.

**Comment by puppetmaster-** [comment]
great idea, in godot you can define action that are mapped to buttons or axis in the background

as an example
action "jump" for [W] , [SPACE] or [ up arrow ]

**Comment by 17cupsofcoffee** [comment]
The slightly tricky thing will be how virtual buttons handle 'pressed' and 'released' events - I feel like if you have two keys bound, then press both of them down one after the other without releasing them, that should just give you one 'pressed' event rather than two (since conceptually, the 'virtual button' was already down after the first key was pressed).

Going to have a go at implementing this tonight...

**Comment by 17cupsofcoffee** [comment]
An update on how this is going - I have a working (if slightly bare-bones) implementation, but the tricky bit is how we hook it into the game loop. We only want to update the input's state once per tick (because calculating 'pressed'/'released' gets really complex/expensive if we try to do it stateless-ly), but Tetra doesn't currently have a generic way of saying 'update this every tick'.

The options I can currently think of are:

* Make the user `tick` the input manually at the beginning of the update, like `Animation` - this is the simplest approach, and makes the behavior really clear, but I feel like it'll be ugly if you have a lot of inputs!
* Add a way to 'register' virtual inputs with the engine, which will then automatically be updated every tick.

**Comment by fossegutten** [comment]
I think Inputs should always update before all game logic in the tick. Would be nice to have this automatically update!

Godot input actions are awesome, except they don’t support multiplayer in a clean way. The best feature imo is the Input.get_action_strength(action) which always returns a float with a value from 0.0 - 1.0. Would be nice with something similar here! Booleans are quite clunky in platformers etc.

**Comment by 17cupsofcoffee** [comment]
This *might* be easier to implement (both within Tetra or in external libraries) now that I've added [events](https://github.com/17cupsofcoffee/tetra/blob/master/src/lib.rs#L253) - you can get updates to the input state pushed to you rather than having to pull it.

One of the main issues I had implementing this before was handling the interactions between multiple input types (e.g. if you have a virtual button that can be triggered by a key and a gamepad button, holding down the key and then pressing the button shouldn't cause two 'pressed' events). That's (as far as I can tell) really tricky to do efficiently in a polling based model, but should be pretty simple with events.

I'm probably not going to work on this for 0.3.0 (no more scope creep, I'd like to release it this year 😅), but it's definitely something I'm still interested in doing.

**Comment by fossegutten** [comment]
Oh,  I just realized that you updated input the last week. You already have provided higher-level stuff than what you get in XNA. 

> One of the main issues I had implementing this before was handling the interactions between multiple input types (e.g. if you have a virtual button that can be triggered by a key and a gamepad button, holding down the key and then pressing the button shouldn't cause two 'pressed' events). That's (as far as I can tell) really tricky to do efficiently in a polling based model, but should be pretty simple with events.

Would it be possible to make something like this, to store the previous state of the pressed keys? It is what I used to do in XNA.

```rust
keys_down: HashSet<Key>,
keys_down_previous: HashSet<Key>,

pub(crate) fn cleanup_after_state_update(ctx: &mut Context) {
    ctx.input.keys_down_previous =  ctx.input.keys_down.copy()
    
    ctx.input.keys_pressed.clear();
    ctx.input.keys_released.clear();
```

I am working on a Godot-inspired input action that has to be polled. I am new to rust, but I will share it if I am happy with it 😸 One issue I ran into is that in Godot, all axes are valued from 0.0 to 1.0, which makes it easier to make individual axes mapped together with e.g. a keyboard key (up, down). While an axis in Tetra(and most other frameworks) are from -1.0 to 1.0, and actually represent two actions in most cases ( up + down, left + right). Need to figure out a way to separate the axes into two, probably an enum or a boolean could work :)
 
```
JOY_AXIS_0 = 0 — Joypad Left Stick Horizontal Axis
JOY_AXIS_1 = 1 — Joypad Left Stick Vertical Axis
JOY_AXIS_2 = 2 — Joypad Right Stick Horizontal Axis
JOY_AXIS_3 = 3 — Joypad Right Stick Vertical Axis
JOY_AXIS_6 = 6 — Joypad Left Trigger Analog Axis
JOY_AXIS_7 = 7 — Joypad Right Trigger Analog Axis
```

**Comment by 17cupsofcoffee** [comment]
> Would it be possible to make something like this, to store the previous state of the pressed keys?

That was actually how the pressed/released functionality was implemented until a week ago 😆 I moved away from using a 'previous state' to explicitly storing the key states because it simplified the logic a bit, but the general idea of the code now is the same.

> While an axis in Tetra(and most other frameworks) are from -1.0 to 1.0, and actually represent two actions in most cases ( up + down, left + right)

That's a very good point, hadn't considered that! Will have to think about whether 0.0 to 1.0 axes are something I want to add.

**Comment by fossegutten** [comment]
Here is my attempt to this:
Only works with polling.
I ran into an issue with not being able to checking if a gamepad axis was released or pressed, without storing the previous and current state somewhere. 
I also dont have a good answer to the pressed/released issues either, without storing state.

Feel free to use any code 😃 


https://github.com/fossegutten/tetra_input_action

**Comment by 17cupsofcoffee** [comment]
Closing this issue, as people have proven this can be done well as external libraries, such as the one linked above and https://github.com/tesselode/baton-tetra :)
