### ISSUE TITLE
Consider moving `Vec2` re-export

### ISSUE THREAD

**Issue by 17cupsofcoffee** [17cupsofcoffee/tetra#101]
I'm quite tempted to move the re-export of `Vec2` up to the crate root - it's used in more modules than just graphics (notably gamepad sticks output a `Vec2`), so it seems kinda weird to have to grab it from there.

An alternative would be to export a `tetra::math` module (which could maybe come in handy if we want to add some more math utils?)

**Comment by 17cupsofcoffee** [comment]
While I'm at it, I want to clean up the rest of the `tetra::graphics` module - there's way too many things that live in multiple places, and it makes it confusing to know where to look for things.

I think we maybe want to keep `tetra::graphics::ui`, `tetra::graphics::animation` and perhaps `tetra::graphics::scaling`, and then make the rest of the modules private/re-exported.

**Comment by 17cupsofcoffee** [comment]
In general I want to strike a balance between not having to dig too deep into submodules to `use` stuff, without making the docs totally unreadable...

**Comment by puppetmaster-** [comment]
Yesterday I noticed that both use variants are possible.

use tetra::graphics::Vec2;
use tetra::glm::Vec2;

I was confused when the compiler complained that there was a double entry.

Is it the same and only exported again?

Right now I'm using the Vec2 from glm.

**Comment by 17cupsofcoffee** [comment]
Yep, they're the same :)

**Comment by 17cupsofcoffee** [comment]
I've renamed `tetra::glm` to `tetra::math` to better describe its function, and moved the export of `Vec2` there. I've also added a bit of a 'cheat sheet' of the most common types and functions to the module.
