### ISSUE TITLE
A few game states

### ISSUE THREAD

**Issue by VladimirMarkelov** [17cupsofcoffee/tetra#102]
Hi!

Thank you for your library - it looks promising and I'd like to give it a try. Moreover, it the only library(from I tried) that does not use winit and, thanks to it, does not fail on start with error "xinput1_4.dll not found"(I'm still on Window 7).

Could you provide a simple example of how to create an app with a few game states with switching between them? Very simple one, like a simple "menu" - one image/button, after it is clicked, some animation starts(e.g, flying bunny from example); on ESC the app is back to "main menu" etc.

**Comment by 17cupsofcoffee** [comment]
Thanks for trying out Tetra :)

Currently I don't have any example code for switching between game states (the engine isn't very opinionated about how you manage that kind of thing), but I agree, it'd be nice to have. I'll try and add a title screen to one of the examples at some point!

**Comment by 17cupsofcoffee** [comment]
I'll leave this issue open until I've written a proper runnable example, but here's how I'd go about implementing this:

```rust
struct TitleScene { 
    // add your title scene assets/state here
}

impl TitleScene {
    // add your title scene logic here
}

struct GameScene { 
    // add your game scene assets/state here
}

impl GameScene {
    // add your game scene logic here
}

// define an enum to represent all the scenes in your game
enum Scene {
    Title(TitleScene),
    Game(GameScene),
}

// add it as a field on your top level state object
struct GameState {
    active_scene: Scene,
}

// dispatch to the active state
impl State for GameState {
    fn update(&mut self, ctx: &mut Context) -> tetra::Result {
        match self.active_scene {
            Scene::Title(scene) => scene.update(ctx),
            Scene::Game(scene) => scene.update(ctx),
        }
    }

    fn draw(&mut self, ctx: &mut Context, dt: f64) -> tetra::Result {
        match self.active_scene {
            Scene::Title(scene) => scene.draw(ctx, dt),
            Scene::Game(scene) => scene.draw(ctx, dt),
        }
    }
}
```

There's lots of different ways you could tweak this - e.g. I commonly see people use a 'stack' of states that they can add to and remove from. The best way depends on what kind of game you're making, I imagine!

Hope that helps, @VladimirMarkelov :)

**Comment by VladimirMarkelov** [comment]
Thank you a lot! That's a good start for me. 

I'm thinking of rewriting my old game(Pygame) into Rust. In Python it was easy to manage state: I used a simple state machine to reassign current state. But as for Rust, I had no clue about ways to implement it.

**Comment by 17cupsofcoffee** [comment]
One of the addon libraries for GGEZ has a good example of how to extend this pattern into more of a state machine type thing - might give you an idea of the direction to go in :) https://github.com/ggez/ggez-goodies/blob/master/src/scene.rs

**Comment by VladimirMarkelov** [comment]
Thanks for the link. GGEZ version looks more complex. I think, I stick to something simpler like your version as the first step :)

**Comment by 17cupsofcoffee** [comment]
I've updated the `tetras` example to have a title screen, as a demonstration of how to implement this kind of thing :)
