### ISSUE TITLE
Implement primitive shape drawing

### ISSUE THREAD

**Issue by 17cupsofcoffee** [17cupsofcoffee/tetra#103]
As requested by various people, most recently @xla on Twitter.

I need to have a look at how the other Rust game libraries do this - I vaguely remember Icefoxen singing the praises of how well Lyon had worked for GGEZ...

**Comment by SymenTimmermans** [comment]
Would this include drawing single pixels in your opinion? I can imagine the primitive shapes implementing Drawable, but plotting single pixels basically only needs a vec2 position and a color. I think being able to draw single pixels easily  is a great addition to the engine.

**Comment by 17cupsofcoffee** [comment]
Yeah, plotting single pixels/writing raw data to a texture is something I'd like to add at some point. I might have a look at it after 0.3 is done!

**Comment by 17cupsofcoffee** [comment]
![](https://media4.giphy.com/media/FoH28ucxZFJZu/giphy.gif)

Basic shape rendering support has been released in 0.5.8.
