### ISSUE TITLE
Implement cameras/views

### ISSUE THREAD

**Issue by 17cupsofcoffee** [17cupsofcoffee/tetra#104]
Another one suggested by @xla on Twitter.

This probably wouldn't be too hard to implement out of tree if someone's game required it, but it's such a common requirement that we probably want it built-in.

**Comment by xla** [comment]
Just out of curiosity what would be the way you'd recommend to achieve this when done outside of the engine?

**Comment by 17cupsofcoffee** [comment]
For something super simple you could just draw everything with an offset (I'd hazard a guess this is what [Mankojai](https://puppetmaster.itch.io/mankojai) did), or you could use a matrix, which would allow you to do stuff like rotations and zooms. The latter is probably what will get baked into Tetra eventually?

In both cases you could either do it directly in your code (easy, but potentially slow in debug mode, especially if you start doing matrix math) or write a [custom shader](https://docs.rs/tetra/0.2.12/tetra/graphics/shader/struct.Shader.html) that takes in your camera transform/matrix.

With regards to matrices and vector math - the entirity of the [`nalgebra_glm`](https://www.nalgebra.org/rustdoc_glm/nalgebra_glm/index.html) library is re-exported in Tetra through the `tetra::glm` module - that's where you'll find the `Mat4` matrix type, along with a buttload of other stuff. The docs don't advertise this very well at the moment; that's something I need to fix!

**Comment by xla** [comment]
Thanks for the thorough response!

> For something super simple you could just draw everything with an offset (I'd hazard a guess this is what [Mankojai](https://puppetmaster.itch.io/mankojai) did), or you could use a matrix, which would allow you to do stuff like rotations and zooms. The latter is probably what will get baked into Tetra eventually?

This is more or less what I ended up using for now. I implemented `Drawable` on my Console/Grid and pass the camera (Vec2 at the moment) with `.position`. Works well enough for now and will probably bite me once/if I want to have zoom as a camera feature.

**Comment by xla** [comment]
Scratch the last comment, implemented zoom as well with `DrawParams.scale` and adjusting the position of the texture accordingly.

**Comment by 17cupsofcoffee** [comment]
Aha, that sounds like a decent plan :)

I imagine something that simple will satisfy a lot of people's use cases, so I want to be careful not to bake anything too complicated into the engine (or at least, I want to make it easy to just ignore it entirely if you don't want it 😄)

**Comment by xla** [comment]
A thought after sleeping on it. Usually a global camera is not desirable as some elements should be sticky (mostly UI elements) and therefore if you have a general view transformation on window (i.e. quicksilver) you have to correct the perspective for UIs, so the inverse problem of partially applying a tansformation to elements that are affected by the camera. Which is not to say that a global transformation/shader on the window isn't nice for other reasons.

Looking at how my structure usually looks like it evolves around layers (map, entities, ui, debug). Which could be a feasible API, having the notion of layers - also to encode some form of z-index - and have each layer be able to take transformations (`DrawParams` would work perfectly for that). Maybe tho this can all just live in the app layer as thin wrapper around `graphics::draw`.  Just wanted to leaave it here for your consideration.

**Comment by 17cupsofcoffee** [comment]
Yeah, that's a good point! Whatever the solution I come up with, I definitely want it to be easy to draw *some* stuff with a transform and then some stuff without. I should probably work that into the example code when I implement this.

Your idea of layering things lines up quite a lot with how I like to structure things too - I'm just very wary of rushing to put anything around how to structure your game into the library itself, because Rust makes it quite easy to design yourself into a corner with that kind of thing. Going to experiment (and see what other people's games look like!) and see what works :)

**Comment by jlauener** [comment]
Totally agree a camera would be nice. It has been the first thing I found missing in Tetra. Currently working around it by adding an offset to draw operations. Not sure Tetra should have the notion of layer though as this seems quite an high level feature specific to the game/application.

One way I see it is that there could be a graphic::set_offset(ctx, offset) call that sets an offset to subsequent draw calls. There could be other functions for rotation, scale and resetting the transform. There could even be a generic call that takes a transformation matrix. This is just my personal opinion as I do think Tetra should remains as simple and close to the metal as possible.

Another way, maybe closer to the notion of layer (and Canvas in Tetra) would be to have something like XNA's SpriteBatch.

(Unrelated to the issue, but I also agree that having a way to Z order sprites could be very useful in some situations.)

**Comment by 17cupsofcoffee** [comment]
Yep, I totally agree with pretty much everything you said :)

LibGDX has a `setProjectionMatrix` function, and the built in `OrthographicCamera` type just gives you something you can pass into that - that seems like it might be a good approach? Would mean that if people decide my `Camera` type is rubbish, they can write their own 😛 

Funnily enough, the `graphics` API in Tetra is actually pretty much a straight port of XNA/LibGDX's `SpriteBatch` classes - the batching just happens behind the scenes as you draw, rather than being something you explicitly have to opt into. I've considered pulling that stuff out into a `SpriteBatch` struct, but at the minute it doesn't feel like it'd add a lot of value.

Generally I just tend to use the order of the draw calls to determine Z ordering (i.e. everything gets drawn from the back to the front). I'm sure there's situations where that's a bit too basic though!

**Comment by 17cupsofcoffee** [comment]
The first step towards this is done - you can now call `graphics::set_transform_matrix` to apply a transformation to all subsequent rendering calls. I'm working on a basic `Camera` struct to go along with it, but you should be able to roll your own pretty easily too.

**Comment by 17cupsofcoffee** [comment]
A simple first draft of the `Camera` API has been added, along with some [example code](https://github.com/17cupsofcoffee/tetra/blob/master/examples/camera.rs). Let me know if this looks like it'll fit your needs!
