### ISSUE TITLE
Implement render textures/framebuffers

### ISSUE THREAD

**Issue by 17cupsofcoffee** [17cupsofcoffee/tetra#107]
Most of the groundwork for this is already there (Tetra always renders to a framebuffer in order to support screen scaling), just needs exposing with a nice API. Open question - should there be a specific RenderTexture object, or should it be possible to render to any Texture?

I ran into a need for this during my 7DRL (which unfortunately remains unfinished due to work). Drawing the console was slow (especially in debug mode), and big performance gains could be made by just redrawing the parts of the screen that changed, but this relied on me never calling glClear. It would have been nicer to just update a texture instead.

**Comment by xla** [comment]
Had the same experience, getting more control what about what to re-render would help a lot. What are the drawbacks with rendering to any texture?

**Comment by 17cupsofcoffee** [comment]
I don't think there'd be any drawbacks usage-wise, just worry it might be a little inflexible in terms of the API (e.g. what if I want to add a method that can only be called on render textures, not normal textures?) That said, I might be overthinking it :p

**Comment by 17cupsofcoffee** [comment]
Ah, actually also - there's some GL state associated with a framebuffer that we have to hold on to, and rendering to arbitary textures might make that a little trickier? I need to have a look at how other libraries handle it :)

Edit: This also seems relevant - https://software.intel.com/en-us/articles/opengl-performance-tips-swap-frame-buffer-objects-fbo-instead-of-surfaces-using-a-single

**Comment by 17cupsofcoffee** [comment]
This is 90% done on my local branch (despite some [interesting issues](https://twitter.com/17cupsofcoffee/status/1106988690931372033) on my first pass 😅) - all being well it should be in 0.2.14.

**Comment by 17cupsofcoffee** [comment]
...and it's merged! 🎊 Little bit barebones for now, but for basic off-screen rendering/post-processing it seems to do the job.
