### ISSUE TITLE
Disable the internal framebuffer when the screen scaling mode is set to Resize

### ISSUE THREAD

**Issue by 17cupsofcoffee** [17cupsofcoffee/tetra#108]
`ScreenScaling::Resize` is effectively the same behaviour you'd get without any scaling at all, so there's no point us adding the overhead of rendering to a framebuffer. In 0.3, I might make this the default.

**Comment by 17cupsofcoffee** [comment]
In fact, perhaps the screen scaling functionality should be pulled out of the core of the engine and made into a drawable of its own?

**Comment by xla** [comment]
For some background when evaluating different rust engines one of the re-occuring issues that was working well in tetra was weird scaling and lack of control of resolution.

What API would you have in mind? And what are the actual upsides of that?

**Comment by 17cupsofcoffee** [comment]
Not sure what the API would look like yet, but the upside would be that the renderer code would be a bit simpler, since it'd not have to juggle between the window backbuffer, its own internal canvas, *and* potentially a user-supplied canvas (for off-screen rendering). It'd only have to care about the former and the latter, and the scaled screen would become just another type of canvas.

EDIT: Another potential benefit is that it would make it a lot easier to draw UI on top of a scaled screen - at the minute if you enable screen scaling, *everything* gets scaled. I'd really like a way to be able to opt in to it on a more fine grained basis!

That said, good screen scaling/resolution control is extremely important to me, and I definitely wouldn't make this change if it'd comprimise that/make that less ergonomic! It was definitely a big 'perhaps' :p 

The only change I'm fairly set on doing is adding a way to disable the internal framebuffer - otherwise if you want to implement your own version of screen scaling (or something like that), you'd still have the overhead of Tetra's framebuffer. Plus `ScreenScaling::Resize` is a bit of an odd one out both in terms of behaviour and implementation - it doesn't scale anything! My thinking is that the scaling mode will turn into `Option<ScreenScaling>` in 0.3, and `None` will be equivilant to `ScreenScaling::Resize` in 0.2. Or something like that :p

**Comment by 17cupsofcoffee** [comment]
This is now done on `master` - when the scaling mode is set to `ScreenScaling::Resize`, no framebuffer is created until you switch to a mode that requires it.

I'm still going to leave this open until I've figured out the final API...

**Comment by 17cupsofcoffee** [comment]
Okay, I tried the 'screen scaling as a drawable' approach and *wow* it makes things so much simpler.

From the API user's perspective, it's a fairly small change, and I think it makes it clearer what's going on:

```rust
graphics::set_canvas(ctx, self.scaler.canvas());

// Do the rest of your drawing here...

graphics::reset_canvas(ctx);
graphics::draw(ctx, &self.scaler, Vec2::new(0.0, 0.0));
```

This is identical to how you'd use a canvas for post-processing in today's Tetra - the only difference is that this wrapper handles scaling for you as well.
