### ISSUE TITLE
Error: Sdl("glXSwapIntervalMESA failed")

### ISSUE THREAD

**Issue by Sispheor** [17cupsofcoffee/tetra#109]
On Ubuntu 18.04
```
cargo run --example animation  
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
     Running `target/debug/examples/animation`
Error: Sdl("glXSwapIntervalMESA failed")
```

**Comment by 17cupsofcoffee** [comment]
Interesting - judging by a [similar issue](
https://github.com/ggez/ggez/issues/294) raised on the old SDL-based version of GGEZ, it seems like this issue occurs when SDL is unable to set the swap interval (i.e, enabling vsync).

If you do `.vsync(false)` when creating the context, does that fix the issue?

**Comment by Sispheor** [comment]
No, same output.
But like the issue you mentioned, I run in a VM on VMware workstation.

**Comment by 17cupsofcoffee** [comment]
Closing in favour of #290, as this seems to be affecting other platforms too.
