### ISSUE TITLE
suggestion to rename, so that it is equal to texture and sound

### ISSUE THREAD

**Issue by puppetmaster-** [17cupsofcoffee/tetra#112]
suggestion to rename from **from_data** to **from_file_data**
https://github.com/17cupsofcoffee/tetra/blob/71ad9c1c1a4a985d9c88ebe5b7a4cbfa9e5df5fb/src/graphics/text.rs#L65

**Comment by 17cupsofcoffee** [comment]
Whoops, missed this one - will deprecate in the next version and add a `from_file_data` :)

**Comment by 17cupsofcoffee** [comment]
Done in 3024842, thanks for spotting the inconsistency :)

**Comment by puppetmaster-** [comment]
you are fast :)
