### ISSUE TITLE
Add a way of building arbitrary geometry

### ISSUE THREAD

**Issue by 17cupsofcoffee** [17cupsofcoffee/tetra#113]
LibGDX and Love2D both have a `Mesh` type that's effectively a nice wrapper around a vertex buffer and an index buffer. Having this in Tetra would be useful for a number of reasons:

* It'd be a nice low level building block for stuff like primitive shapes (#103)
* It could potentially be used to generalize some of the code from the renderer
* I'd like to implement an imgui renderer for Tetra as a seperate crate, but that would need some way of building the geometry without touching the renderer internals

One potential stumbling block here is that the renderer in Tetra currently *only* handles quads. We also might get into a bit of a chicken and egg situation - if `Mesh` relies on the batcher to draw, can we use it in the batcher implementation?

**Comment by McGittyHub** [comment]
This would be a much needed feature. Having a solution to ui and procedural mesh generation, is pretty important.

**Comment by 17cupsofcoffee** [comment]
This is (finally!) available on the `main` branch, and will be released in the next version of Tetra.

**Comment by 17cupsofcoffee** [comment]
Released in 0.5.4!
