### ISSUE TITLE
Add a module with common math functions (e.g. lerp)

### ISSUE THREAD

**Issue by 17cupsofcoffee** [17cupsofcoffee/tetra#114]
I find myself rewriting these a lot, and other libraries have them, so I think it's worth adding. 

Bonus: if we have a `tetra::math` module, that solves the problem of where to put the `Vec2` re-export (#101).

Prior art;

* XNA's [MathHelper](https://github.com/FNA-XNA/FNA/blob/master/src/MathHelper.cs) class
* LibGDX's [MathUtils](https://libgdx.badlogicgames.com/ci/nightlies/docs/api/com/badlogic/gdx/math/MathUtils.html) class
* Otter's [Util](https://bitbucket.org/kylepulver/otter/src/578e5a9b3f3830cbb2ebf583f94b412e880567c5/Otter/Utility/Util.cs?at=default&fileviewer=file-view-default) class

**Comment by 17cupsofcoffee** [comment]
Open question - how generic do these helpers want to be? I could add a trait for each one, which would allow for multiple types to be passed in, but I don't know how much value there is in that.

Also worth noting that nalgebra's vector types already provide `lerp` and similar methods.

**Comment by xla** [comment]
Why not piggyback on nalgebra instead of a native tetra module?

**Comment by 17cupsofcoffee** [comment]
Yeah, I might just say *'use `myVec.lerp(other, amount)` from nalgebra'* for vectors.

In that case, `tetra::math::lerp` would probably only need to handle `f32`, which would simplify things a lot :) That's actually pretty much exactly how it works in XNA (methods for math operations on vectors, static functions for math operations on primitives), so there's precedent.

EDIT: Plus if we did ever want to extend the functions to be generic, I think could be done in a backwards compatible way, so probably not worth rushing into that.

**Comment by 17cupsofcoffee** [comment]
Upon further inspection, nalgebra-glm *already* has functions for doing things like [lerp](https://www.nalgebra.org/rustdoc_glm/nalgebra_glm/fn.lerp_scalar.html) and [clamp](https://www.nalgebra.org/rustdoc_glm/nalgebra_glm/fn.clamp_scalar.html) on generic numbers 😅

I think I'd be better off adding better documentation for this rather than duplicating the functionality in Tetra itself.
