### ISSUE TITLE
NineSlice: would like to change texture, height and width at runtime

### ISSUE THREAD

**Issue by puppetmaster-** [17cupsofcoffee/tetra#116]
I want to use the NineSlice for some simple ui elements and get them to scale themselves. 
It would be nice if there was the possibility that I could change the texture, height and width at runtime.
Would that be possible?
https://github.com/17cupsofcoffee/tetra/blob/5730da37d9a2d748a97c8b4f31db9bcd8d5167f2/src/graphics/ui.rs#L10

**Comment by 17cupsofcoffee** [comment]
There's no technical reason why this can't be done, I just haven't implemented it yet :) I will add it in the next version.

**Comment by 17cupsofcoffee** [comment]
0.2.15 has just been released with this functionality included - I also added similar stuff to `Text` and `Animation`, for the sake of consistency.

**Comment by puppetmaster-** [comment]
👍 thanks for the quick implementation
