### ISSUE TITLE
Implement a platform abstraction layer

### ISSUE THREAD

**Issue by 17cupsofcoffee** [17cupsofcoffee/tetra#122]
This is a general tracking/discussion issue for the idea of adding an abstraction layer over the top of some (all?) of the backend libraries we use. This would (hypothetically):

* ...make it easier to switch out libraries later.
* ...allow users to disable bits of the context they're not using (e.g. if you don't have gamepad support, why waste processing time handling those events?).
* ...open up a vague pathway to getting Tetra running on WASM.

This probably won't be a publicly exposed API to begin with, as I don't trust myself to get it right first time - but if we could have e.g. all of the SDL code in one place, it'd probably clean up the codebase quite a bit.

**Comment by puppetmaster-** [comment]
I am for everything that brings Tetra closer to a WASM build.

**Comment by 17cupsofcoffee** [comment]
Fair warning, that might be a long way off 😅 But I'm definitely looking into it.

**Comment by 17cupsofcoffee** [comment]
Phase one of this work is now done! 🎉

All of the SDL code (barring a few re-exported types which will need replacing in Tetra 0.3) is now located in the [`platform`](https://github.com/17cupsofcoffee/tetra/blob/master/src/platform.rs) module. I'm sure there's still lots of bits of the code that rely on the assumption that SDL will always be there, but this is a good first step towards figuring out what those bits are :)

This *should* be a completely transparent change for end-users of Tetra, but I'm going to try and build some projects like Shoot Out Your Life on the master branch and make sure I haven't broken anything. Won't release it until then!

**Comment by 17cupsofcoffee** [comment]
This was merged as part of 0.2.20 :) Still need to do some work to extract out the audio backend, but I think that probably deserves a seperate issue.
