### ISSUE TITLE
Add a way of creating a color out of integer RGB values

### ISSUE THREAD

**Issue by aaneto** [17cupsofcoffee/tetra#123]
I believe it is desirable to have a constructor of color that takes u8 numbers as input, such as:
```rust
let color = Color::rgbi(80, 80, 80);
// or
let color_alpha = Color::rgbai(80, 80, 80, 255);
```

Honestly though, I'm pointing this because its my personal preference.

**Comment by 17cupsofcoffee** [comment]
Adding `rgb8` and `rgba8` constructors to `Color` is definitely something I want to do, I just haven't gotten around to it yet. Might add it this weekend, if I get chance :)
