### ISSUE TITLE
Allow suppressing of display info of the OpenGL driver and vendor information.

### ISSUE THREAD

**Issue by m-sz** [17cupsofcoffee/tetra#132]
Hello! Thanks for the great project which is this game framework. It is really easy and simple to use, while having great architectural choices (fixed timestep, and so on).

I have only encountered one issue which i would like to have more control over. For me it would be great to be able to **not** print the OpenGL vendor information, because i would like to have my own, custom diagnostic information printed at a later time during the application's work.

**Comment by 17cupsofcoffee** [comment]
Thank you for the kind words! If you end up publishing any projects/code, please let me know - can add them to the [showcase](https://tetra.seventeencups.net/showcase) page on the website :)

I definitely want to add a way of surpressing this output (or perhaps just turn it off by default), especially given that it currently shows up in release mode. It's kind of tied in with the work I've been planning in #87, but it shouldn't be dependent on that.

A related question - do you have a way of accessing this diagnostic information easily in your game, for your own display? Or would it be helpful for Tetra to give you access to it (e.g. through the `window` module)?

**Comment by m-sz** [comment]
Indeed it would be very helpful if tetra could expose its inner 'components' through the API. I belive that it can provide useful information debugging problems on various platforms.

**Comment by 17cupsofcoffee** [comment]
Going to have a crack at fixing this tonight - general approach will be:

* Add a getter/setter for the vsync state and getters for the driver/vendor info to `tetra::graphics`.
* Add an off-by-default setting to the config builder to print the debug info at startup.

This should hopefully serve both our use cases:

* If you just need the information quickly to submit a bug report, you can just add `.debug_info(true)` (or something like that) to the config and then take it out again later.
* If you want to surface that info in your game in a custom way, you can use the lower level methods to do so.

**Comment by 17cupsofcoffee** [comment]
This is now available on master via `graphics::get_device_info`. Still need to handle the vsync side of things.

**Comment by 17cupsofcoffee** [comment]
Done!
