### ISSUE TITLE
How to use DrawParams::rotation correctly?

### ISSUE THREAD

**Issue by VladimirMarkelov** [17cupsofcoffee/tetra#133]
How should texture rotation work? And how to use it with animation correctly?

My use case: I wanted to draw an animated arrow that pointed either to left or to down. So, I creates a single texture with 4 frames on that the arrow pointed down. I expected that `rotate` would rotate within a frame but it was not. When I changed direction I had to change draw position as well. Simplified example (the game screen is divided into blocks each of them CELL_SIZE x CELL_SZIE pixels, each arrow frame has the same dimensions CELL_SIZE x CELL_SIZE):

```rust
// in update function I calculate the arrow direction and position
self.arrow_dir = self.calc_direction();
self.arrow_pos = if self.arrow_dir == Direction::Down {
  Vec2(x, y)
} else {
   // the case when the sprite rotates. I had to fix 'x' position to see 
   // the arrow displayed at the same position as in `Down` case
  Vec2(x + CELL_SIZE, y)
};

// in draw function
let angle = if self.dir == Direction::Down { 0.0 } else { PI / 2.0 };
graphics::draw(
  ctx, &self.arrow_animation,
  DrawParams::new().position(self.arrow_pos).rotation(angle)
)
```

P.S. At first, I thought of changing `origin` - my assumption was that it is a center of rotation. But after setting origin to the frame center `origin(CELL_SIZE/2.0, CELL_SIZE/2.0)` it got worse. Then I read the docs and it seemed to me that origin is not for "correcting" rotation.

Thanks!

**Comment by 17cupsofcoffee** [comment]
Your original idea was correct - if you want to change the center of rotation, you should set the origin (e.g. for a 16x16 frame, the origin would be 8.0, 8.0). I see why the docs would make you think otherwise, it's not phrased very well - will need to fix that!

If you can't get `origin` to work, could you share the code where you tried to use it?

**Comment by 17cupsofcoffee** [comment]
One other thing that might be tripping you up - the position of a sprite is relative to the origin. So for example, if you set the origin to the centre, and then draw at (0, 0), the centre of the sprite will be at the top left of the screen.

Also note that if you just want to mirror the texture horizontally or vertically without changing the pivot point, setting the scale to -1.0 on one or both axes will do that.

**Comment by VladimirMarkelov** [comment]
I'll try to do it once more and paste my code if it does not work :)

**Comment by VladimirMarkelov** [comment]
I found out what confused me :) I did not expect that to rotate correctly I had to do two things: (a) set origin and (b) fix drawing position. Moreover, it requires to be careful when moving the drawing position: "x" must be decreased by origin.x, while "y" must be increased by origin.y. So, I finally managed to draw correctly with this piece of code:

```rust
let origin= Vec2::new(BRICK_SIZE/2.0, BRICK_SIZE/2.0);  // 1
let pos = Vec2::new(arrow.pos.x - origin.x, arrow_pos.y + origin.y); // 2 
.... DrawParams::new().position(pos).origin(origin).rotation(rotate), ... 
```

My original expectation was that line `//1` was enough and when I saw my arrow in "weird" position I just "fixed" position without using `origin`.

The issue can be close as "solved" as I know now how to do rotation correctly :) Though, it took some time to find it out.

**Comment by VladimirMarkelov** [comment]
"weird" position was just a position between blocks:

![half_origin](https://user-images.githubusercontent.com/1577186/65367687-fc674500-dbe9-11e9-991e-2d1d1e2043b2.gif)

now I see that it looked weird because I draw everywhere at the position in blocks multiplied by block size.

**Comment by 17cupsofcoffee** [comment]
Glad you were able to figure it out :) I definitely think this needs to be documented better - will raise another issue to track that.
