### ISSUE TITLE
Write a migration guide for 0.3

### ISSUE THREAD

**Issue by 17cupsofcoffee** [17cupsofcoffee/tetra#134]
0.3 is becoming an increasingly breaking change - would be a good idea to have a page on the website documenting what needs to be changed to upgrade.

**Comment by 17cupsofcoffee** [comment]
@puppetmaster- Since you thumbs-up-ed this issue, a question - do you think [the details in the changelog](https://github.com/17cupsofcoffee/tetra/blob/master/CHANGELOG.md#upcoming) would suffice as a kind of migration guide, or do you think more detail is needed?

At the very least, I'd like to go through and mark which changes in that file are breaking, so people can immediately spot what might affect them. I also might get MDBook to pull through the file, so that it gets displayed in a nicer format on the website.

**Comment by fossegutten** [comment]
The changelog looks sufficient to me, even as a new user of Rust and Tetra!

**Comment by puppetmaster-** [comment]
changelog together with the changed examples is good for me

**Comment by 17cupsofcoffee** [comment]
👍 I might also write up a blog post with some of the big changes.

**Comment by 17cupsofcoffee** [comment]
The changelog is now published at https://tetra.seventeencups.net/changelog, as well as in the GitHub repo. It'll update once 0.3 releases!
