### ISSUE TITLE
On Linux, graphics::clear() does not behave properly, when having drawn a Canvas

### ISSUE THREAD

**Issue by SymenTimmermans** [17cupsofcoffee/tetra#140]
Somehow, on Linux, if you draw to a canvas, and then draw the canvas to the screen, you can not fully clear the screen. 

When I call graphics::clear(), I expect the screen to be empty, so I can redraw my interface. However, the pixels from an earlier drawn Canvas are not cleared. 

I modified the Hello World code to reproduce this:

```
    fn draw(&mut self, ctx: &mut Context, _dt: f64) -> tetra::Result {
        graphics::clear(ctx, Color::rgb(0.01 * self.iter, 0.584, 0.929));

        let fg = Canvas::new(ctx, 1280, 720);
        let bg = Canvas::new(ctx, 1280, 720);
        graphics::set_canvas(ctx, &fg);
        graphics::draw(ctx, &self.text, self.position + Vec2::new(0.0, self.iter));

        graphics::set_canvas(ctx, &bg);
        graphics::draw(ctx, &self.text, self.position + Vec2::new(0.0, 40.0 + self.iter));

        graphics::reset_canvas(ctx);

        // draw background canvas to screen
        graphics::draw(ctx, &bg, Vec2::new(0.0, 0.0));

        // draw the original text
        graphics::draw(ctx, &self.text, self.position + Vec2::new(0.0, 20.0));

        // draw foreground canvas to screen
        graphics::draw(ctx, &fg, Vec2::new(0.0, 0.0));

        Ok(())
    }
```

See full file in attachment. 

I added two canvases, `fg` and `bg `, which also contain the moving text, yet positioned on other y-coordinates, so we can tell them apart.
To be discover whether the canvas is initially empty, we render the canvas a bit lower every loop. At first I thought the Canvas framebuffers were not cleared, but I can now tell they are.

Where the middle text is moving nicely, and the old pixels are cleared in graphics::clear, the top and bottom texts, which are first rendered to a Canvas, are not cleared on graphics::clear. So remnants of those draws remain on the screen. 

This looks like:
![canvasbug](https://user-images.githubusercontent.com/8511860/66136184-55c47080-e5fb-11e9-99fb-f06fd40d30bb.png)

I have been looking at the Tetra code, but I can't find an obvious cause of this behaviour. 

I tried a workaround, where I call graphics::clear after I set the render canvas. With one extra canvas layer, it seems to work, but with more than one canvas layer, there is weird behaviour and flickering, and all hope is lost...
[tetra_linux_test.tar.gz](https://github.com/17cupsofcoffee/tetra/files/3686709/tetra_linux_test.tar.gz)

**Comment by SymenTimmermans** [comment]
This is on Arch Linux x64 with the following OpenGL version:

OpenGL Device: Mesa DRI Intel(R) Haswell Mobile 
OpenGL Driver: 4.5 (Core Profile) Mesa 19.2.0

**Comment by 17cupsofcoffee** [comment]
I think I see the problem! You're recreating the `Canvas` objects every frame - they're pretty expensive to create, so it's rare that you should ever need/want to do this.

Also note that calling `clear` will only clear the current render target, so if you want to clear your canvases *and* the screen, you'll need to call it once for each. I think you can use `Color::rgba(0.0, 0.0, 0.0, 0.0)` if you want to clear the canvas but keep it transparent? I've not tried it though!

Your code should look more like this:

```rust
    fn draw(&mut self, ctx: &mut Context, _dt: f64) -> tetra::Result {
        graphics::set_canvas(ctx, &self.fg);
        graphics::clear(ctx, Color::rgb(0.01 * self.iter, 0.584, 0.929));
        graphics::draw(ctx, &self.text, self.position + Vec2::new(0.0, self.iter));

        graphics::set_canvas(ctx, &self.bg);
        graphics::clear(ctx, Color::rgb(0.01 * self.iter, 0.584, 0.929));
        graphics::draw(ctx, &self.text, self.position + Vec2::new(0.0, 40.0 + self.iter));

        graphics::reset_canvas(ctx);
        graphics::clear(ctx, Color::rgb(0.01 * self.iter, 0.584, 0.929));
        graphics::draw(ctx, &self.bg, Vec2::new(0.0, 0.0));
        graphics::draw(ctx, &self.text, self.position + Vec2::new(0.0, 20.0));
        graphics::draw(ctx, &self.fg, Vec2::new(0.0, 0.0));

        Ok(())
    }
```

Hopefully that resolves your issue? If so, I'll leave this open as a reminder to document this better!

**Comment by SymenTimmermans** [comment]
Thanks so much for your quick response!

Your suggestion works! I created a Vec<Canvas> in the Gamestate, which initializes the layers (creates the canvases) I need in the ::new() function. 

In the draw functions, I made sure each canvas is cleared, like you said, with `Color:rgba(0.0, 0.0, 0.0, 0.0)`. Pretty straightforward.

It's hard to say if this is a bug or expected behavior, and whether I could have avoided this if the documentation were better... I did not experience these issues on Windows but maybe I just got lucky.

Anyway, thanks for helping me resolve this.

**Comment by 17cupsofcoffee** [comment]
Yeah, I must admit, I'm not sure why creating the canvases every frame led to such weird graphical glitches 😅 I'll take a look at your original code at some point and see if I can replicate.

At the very least though, I definitely need to add a big "don't create canvases in `draw`!" message into the docs :) I know I've made similar mistakes in other frameworks before.

**Comment by 17cupsofcoffee** [comment]
I've added a note to the docs, as well as some example code that demonstrates proper usage of the API.
