### ISSUE TITLE
Switch from nalgebra-glm to... something else?

### ISSUE THREAD

**Issue by 17cupsofcoffee** [17cupsofcoffee/tetra#142]
`nalgebra` is too crazy with the generics, and it makes the documentation unreadable for the actual struct/trait methods. That's a fine trade-off for them to make, but given that Tetra is fairly explicitly targeted as being a simple/beginner's engine, it just doesn't sit well with me. So I think I'm going to switch to `glam` - the docs are simpler, and  the benchmarks seem faster.

The main thing we'd lose from this is the helper functions, but I can rewrite those myself (which would also be more futureproof if we ever have to switch math libraries again).

Maybe we could also switch to using the `mint` interop types? Then people could keep using `nalgebra` in their games if they really want to, and we wouldn't lose support for stuff like `nphysics`.

**Comment by 17cupsofcoffee** [comment]
This is kind of a duplicate of #114 in a way - that was harder to justify when the library we were using came with a load of functions out of the box, but I think this gives us an opportunity to simplify things (e.g. Do we really need three `lerp` functions? Could that just be one generic one, or a trait?)

**Comment by 17cupsofcoffee** [comment]
One potential point of annoyance for me is that `glam` uses getters and setters for the fields of vectors. This is for good reasons (you can't give direct access to the underlying SIMD types), but given that 99% of Tetra users are only gonna care about the `Vec2` type, which *isn't* SIMD-enabled, this seems like a big ergonomics downgrade.

**Comment by StarArawn** [comment]
Just a thought, but switching away from nalgebra might be an annoyance when working with nphysics. I agree though nalgebra uses way too many generics.

**Comment by 17cupsofcoffee** [comment]
Yeah, that's a good point, and I definitely don't want to lock anyone out of the wider ecosystem! The way around that would be to use [`mint`](https://github.com/kvark/mint), but that comes with its own set of tradeoffs (e.g. any API that takes a `Vec2` would now have to take `Into<Vector2>` instead).

I need to mull over the pros and cons of each option - unless I'm 100% happy with a new solution, I'll probably stick with nalgebra and just [paper over the docs limitations myself](https://github.com/17cupsofcoffee/tetra/blob/master/src/math.rs#L1-L33).

**Comment by 17cupsofcoffee** [comment]
Okay, I'm leaning towards switching to [`vek`](https://github.com/yoanlcq/vek), with an option to enable `mint` conversions.
