### ISSUE TITLE
Rendering on MacBook Pro only covers quarter of the screen

### ISSUE THREAD

**Issue by johanlindfors** [17cupsofcoffee/tetra#147]
Running the samples (or anything I build myself) on my MacBook Pro 2015 with 2560x1600 screen resolution, causes all rendering to only cover the lover left quarter of the window, doesn't matter if it's full screen or windowed. Most likely has something to do with DPI settings but I can't seem to impact this with tetra? Have tried to change internal vs external size on window, but nothing seems to change.

Any ideas? SDL2 related I guess, since I do have these issues with "plain" SDL2 projects as well.

**Comment by 17cupsofcoffee** [comment]
This definitely sounds like a DPI issue - the weird thing here though is that I'm not requesting a high DPI window from SDL...

**Comment by 17cupsofcoffee** [comment]
Also, out of curiosity, is there any difference in behaviour between the master branch and the release branch? In 0.2 everything rendered to a framebuffer behind the scenes, interested if that could be related.

**Comment by johanlindfors** [comment]
There's no difference between 0.2 and the current master unfortunately.

**Comment by 17cupsofcoffee** [comment]
That rules out one thing, at least :) When I have some free time I'll see if I can replicate the issue by futzing about with my Windows machine's DPI settings. I do have access to a Macbook, but it's a work machine and I'm not sure if I can get away with installing Rust onto it...

**Comment by johanlindfors** [comment]
I can try that to! It is interesting that I don't get it on my Surface Book...

**Comment by fossegutten** [comment]
Not sure if this helps:

> On Apple's OS X you must set the NSHighResolutionCapable Info.plist property to YES, otherwise you will not receive a High DPI OpenGL canvas. 

https://wiki.libsdl.org/SDL_CreateWindow

**Comment by johanlindfors** [comment]
Revisiting this issue after some investigation today on the master branch. Most of the samples are actually working as expected, however some don't:
These examples doesn't work (they render only in the lower quarter of the window): Canvas, Scaling, Tetras

Now to investigate what makes these sample different.

**Comment by 17cupsofcoffee** [comment]
Ah - those are the only three examples that make use of a `Canvas` (basically a wrapper around an OpenGL framebuffer). I could *perhaps* understand the raw `canvas` example having this behaviour, as that draws the canvas as a fixed size, but `scaling` and `tetras` are meant to automatically scale the screen to fit the window. So something's clearly not right there! That narrows things down a lot, though :)

Merry Christmas/happy holidays, by the way! :smile:

**Comment by johanlindfors** [comment]
Thanks for the prompt response, lets go back to celebrating Christmas now :)

Oh, and when you have some time, feel free to checkout my tutorial on how to build the Snake game with Rust and Tetra. Currently (as of the time of this comment) only published on a specific branch on my repo, but it can be accessed here: https://github.com/programmeramera/snake-in-tetra/blob/dev/tutorial/tutorial/step_1.md

**Comment by 17cupsofcoffee** [comment]
Excellent tutorial :) I'm working on my own one for the website at the minute as well, so it'll be good to compare approaches.

This does seem to be specifically a MacOS issue, as the canvas examples work fine for me when I crank up my DPI on Windows. Hopefully that narrows things down a bit more.

**Comment by johanlindfors** [comment]
I can't reproduce this issue lately, would be interesting to understand what was fixed. I can't really relate any commits directly to this issue, but there have been some updates to backing gl-layer I guess...

Closing for now, keep up the great work!!!

**Comment by johanlindfors** [comment]
My bad, it still occurs, when I use the ScreenScaler or as was mentioned before the Canvas underneath...

**Comment by 17cupsofcoffee** [comment]
I've got a couple of hunches as to what needs fixing here (think it might be to do with how I'm pulling the window size out of SDL) - will let you know when I've had chance to properly investigate 😄

**Comment by 17cupsofcoffee** [comment]
If you make one of the examples that **does** currently work `resizable` (via `ContextBuilder`), does the bug trigger when you resize the window? I've noticed that we never set `glViewport` unless the canvas changes or the window is resized, so I'm wondering if we're setting that incorrectly.

**Comment by johanlindfors** [comment]
You are right, tried with the "camera" example which works just fine, until I resize the window, then it behaves "badly"!.

**Comment by 17cupsofcoffee** [comment]
Aha, progress :smile: So the issue *seems* to be that I'm setting `glViewport` to the incorrect value (Good thing I forgot to do that at startup, I guess 😆).

I think maybe this needs to use SDL's 'drawable size' rather than the 'window size'? [There's words to that effect on the docs.](https://wiki.libsdl.org/SDL_GL_GetDrawableSize) I'll have a play around with that later and create a branch.

**Comment by johanlindfors** [comment]
Let me know how I can help!

**Comment by 17cupsofcoffee** [comment]
Could you add the following lines of code [here](https://github.com/17cupsofcoffee/tetra/blob/master/src/platform/window_sdl.rs#L138), and let me know what gets logged out when you run an example?

```rust
dbg!(sdl_window.size());
dbg!(sdl_window.drawable_size());
```

Currently I'm not explicitly asking for a DPI-aware window from SDL, so I want to make sure that getting the correct drawable size doesn't rely on that being that case. Don't want to do the refectoring if it's not actually going to fix anything 😓 

If the returned drawable size is right, I can thread that data through to `glViewport` and it should hopefully fix your issue 😄 It's also something I was probably going to have to do anyway at some point as a step towards actual high-DPI support.

**Comment by johanlindfors** [comment]
Both of these calls returns the same size, independent of the result.

I run the "camera" sample which works fine until I resize the window, and the "tetras" sample which immediately "breaks".

Was that the expected result?

**Comment by 17cupsofcoffee** [comment]
That was the exact opposite of what I was expecting 😆 *But* it directed me to an issue thread on ioquake3's GitHub that may have a solution!

Apparently in MacOS Catalina, the `NSHighResolutionCapable` plist option defaults to `true`, while on older versions it defaults to `false`. But, as previously mentioned, Tetra currently *doesn't* request a high DPI SDL2 window (because why would it, the engine doesn't handle DPI yet). I think this is putting us in a situation where we're telling SDL and MacOS the opposite thing!

The defaults changing would explain why other Mac users have not run into this issue before (something that's been bugging me since you raised the issue 😛)

So I think, until Tetra has proper support for high DPI rendering, the fix would be to set `NSHighResolutionCapable` to `false` in `Info.plist`? The only issue is that I'm so clueless with Macs that I have no idea how to do that 😆 I'll do some research over the weekend.

I'll also start looking at how much effort it would be to actually handle DPI properly...

EDIT: You might also be able to tick a 'Open in Low Resolution' box in the application's Info panel in Finder, apparently? Obviously doesn't solve the issue for distributing a game, but it's something...

**Comment by jpgadoury01** [comment]
For the time being, perhaps this solution should suffice?
https://wiki.libsdl.org/SDL_SetHintWithPriority
https://wiki.libsdl.org/SDL_HINT_VIDEO_HIGHDPI_DISABLED

**Comment by 17cupsofcoffee** [comment]
Possibly! Although I don't have access to a machine where I can replicate the issue, so someone else would need to test it.

**Comment by GRVYDEV** [comment]
I have found a current "fix" for this. By adding ```sdl2::hint::set_with_priority("SDL_VIDEO_HIGHDPI_DISABLED", "1", &sdl2::hint::Hint::Override);``` at line 62 in src/platform/window_sdl.rs and changing `<key>NSHighResolutionCapable</key>` to `<false/>` in the info.plist the game scales as it should.

**Comment by 17cupsofcoffee** [comment]
@SNELON: Does it only work with *both* of those changes in place? I'd be interested to know the behaviour when only `SDL_VIDEO_HIGHDPI_DISABLED` is changed/when only `NSHighResolutionCapable` is changed.

**Comment by GRVYDEV** [comment]
As far as I know it only works when BOTH are changed. I tried only changing the `SDL_VIDEO_HIGHDPI_DISABLED` hint and that didnt work. This solution only works when I bundle my game with a correct info.plist

**Comment by 17cupsofcoffee** [comment]
Thanks for checking - are you on Catalina, by any chance? I believe prior to that `NSHighResolutionCapable` was `false` by default, but I might be wrong.

**Comment by GRVYDEV** [comment]
Yeah I am currently on Catalina 10.15.15

**Comment by 17cupsofcoffee** [comment]
Ooh - out of interest, have people in this thread tried SDL 2.0.12? It looks like [this might have been fixed on SDL's end](https://hg.libsdl.org/SDL/rev/46b094f7d20e).

**Comment by johanlindfors** [comment]
It sure does work with SDL 2.0.12!

**Comment by johanlindfors** [comment]
So I guess we could close this ticket/issue with the fix being to make sure to use SDL 2.0.12 or later.

**Comment by 17cupsofcoffee** [comment]
Yeah, that would be a better fix than disabling `NSHighResolutionCapable`, as it doesn't require changes to the application's packaging. I'll add a note to the installation page in the docs about this.

EDIT: [Done!](https://tetra.seventeencups.net/installation/#mac)

**Comment by 17cupsofcoffee** [comment]
Quick heads up, since it relates to this issue: Tetra now has experimental support for enabling high-DPI mode on the `main` branch, thanks to #212! It's a bit bare-bones at the minute (effectively it just scales rendering up), but it should at least allow you to get smooth rendering on Catalina/Big Sur without having to mess around with the `Info.plist`.
