### ISSUE TITLE
Expose more window/input events

### ISSUE THREAD

**Issue by 17cupsofcoffee** [17cupsofcoffee/tetra#153]
I've somewhat stubbornly tried to keep the `State` trait as minimal as possible up until this point - that approach is starting to break down, I think.

For example, the camera and scaling APIs need to be kept updated on changes to the window size - the only way to do that with the 0.2 API is to constantly poll for it in `update` or `draw`, which isn't great.

So I'm thinking I might expose more 'hooks' on the `State` trait, for things like resizes, input events, etc. This would be in addition to the existing APIs, rather than replacing anything (e.g. the existing polling input methods will still be available).

**Comment by puppetmaster-** [comment]
That's exactly what I missed in my last game. At the moment you just can't change the window size. :smile:

**Comment by 17cupsofcoffee** [comment]
I've slightly changed the interface for this - there's now a single `event` method, which gets called whenever a window/input event gets fired. There's several reasons for this:

* It's less typing/rework when you want to handle a new kind of event.
* Using an `Event` enum will help me decouple the platform layer, and it'll be more consistent with what I have in mind for custom game loops in the future.
* Due to pattern matching, you don't have to import as many types.
* [The Twitter horde liked it more 😅](https://twitter.com/17cupsofcoffee/status/1201953262385143810)

**Comment by 17cupsofcoffee** [comment]
There is now an event for every window event I'm currently handling (might add more later), and every input method available (in other words, anything you can do with the `input` module you can also now do with events).
