### ISSUE TITLE
Engine crashes if setting timestep to variable

### ISSUE THREAD

**Issue by fossegutten** [17cupsofcoffee/tetra#156]
set_timestep(Timestep::Variable) while running the game, causes the engine to crash

**Comment by 17cupsofcoffee** [comment]
Seems to happen when building a context with variable timestep too - agh 😦 Will investigate.

**Comment by 17cupsofcoffee** [comment]
Agh, there's an infinite loop being caused by `time::is_update_ready`. Should be an easy-ish fix, I'll try to release a 0.3.1 today.

**Comment by 17cupsofcoffee** [comment]
0.3.1 has been released, should fix this issue!
