### ISSUE TITLE
alsa-sys dependency fails on some Linux flavors

### ISSUE THREAD

**Issue by cbzehner** [17cupsofcoffee/tetra#166]
**Summary:**
When attempting to work through the [Pong tutorial](https://tetra.seventeencups.net/tutorial/01-creating-a-project/) on ElementaryOS, an Ubuntu Linux derivative I was unable to build the `tetra` package in my project.

Dependency on `alsa-sys` can cause builds to fail in the correct packages aren't installed. This is probably specific to some but not all Linux distributions.

**Resolution:**
> You can fix this error by installing libasound2-dev with the following command:
> ```sudo apt install libasound2-dev```
> Source: https://github.com/ggez/ggez/issues/100

**Steps to reproduce:**
Running `cargo run` (or `cargo watch`) in this case results in the following error:
```
❯ cargo watch
[Running 'cargo check']
   Compiling alsa-sys v0.1.2
   Compiling rustc_version v0.2.3
error: failed to run custom build command for `alsa-sys v0.1.2`

Caused by:
  process didn't exit successfully: `/home/cbzehner/Projects/arewegameyet/pong/target/debug/build/alsa-sys-ccc713fee0bc9388/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"alsa\"` did not exit successfully: exit code: 1\n--- stderr\nPackage alsa was not found in
the pkg-config search path.\nPerhaps you should add the directory containing `alsa.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'alsa\' found\n"', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
[Finished running. Exit status: 101]
```

**Expected behavior:**
`cargo run` should complete successfully.

**Additional info:**
This can be closed out. I just wanted to document this here in case other people run into it in the future.

The first thing I did to try and resolve this was search the issues for `alsa` here, now if someone in the future follows the same steps they'll get an answer :smile:

**Comment by 17cupsofcoffee** [comment]
This is documented on [the installation page](https://tetra.seventeencups.net/installation/#installing-alsa-linux-only), but you're definitely not the first person to miss it!

I think I need to make it clearer at the beginning of the tutorial that you need to look at that page - it's mentioned *very* briefly, but it's easy to skim past it. If you have any suggestions on how this could be made clearer, I'll definitely look at implementing them.

I'm glad you were able to get it working, anyway! It's funny how many Tetra issues can be solved by looking at GGEZ's issue tracker 😆 Let me know if you run into any more issues while working through the tutorial.

**Comment by cbzehner** [comment]
Thanks! I realized I missed the documentation right after creating this issue :man_facepalming: 

I'm having a blast going through the tutorial though. Thanks for putting it together. I found it via [arewegameyet](https://arewegameyet.com/resources/tutorials/)
