### ISSUE TITLE
Implement DropFile event from sdl2

### ISSUE THREAD

**Issue by McGittyHub** [17cupsofcoffee/tetra#171]
**Summary:**
implement missing DropFile event from sdl2

**Why is this needed?**
This is practical for tools where you want to allow the user to drop a file.

**Comment by 17cupsofcoffee** [comment]
👍 I will have a look at how I could expose this from Tetra's API.

The main consideration would be whether other windowing libraries (and the web) support it, as I'd like to avoid getting too tied to SDL2. I'd imagine they probably do, though!

**Comment by 17cupsofcoffee** [comment]
This is now on the `master` branch, and will be released in the next version! Example code [here](https://github.com/17cupsofcoffee/tetra/blob/master/examples/file_drop.rs).

A couple of caveats with the current implementation:

* As far as I can tell, SDL2 doesn't offer a way of detecting if a file is being 'hovered' over the window prior to dropping it 😢
* If you drop multiple files onto the window, you will get multiple events, one for each file.

**Comment by 17cupsofcoffee** [comment]
Released in 0.3.5 🎉
