### ISSUE TITLE
Add a way to find information about the system

### ISSUE THREAD

**Issue by cralian** [17cupsofcoffee/tetra#175]
**Summary:**
There does not seem to be a way to find information about the system. It would be nice to at least be able to find the screen size before creating the context (or, if not possible, create a context without creating a window first). 

**Why is this needed?**
Code examples show something like
```
ContextBuilder::new("Hello, world!", 1280, 720)
    ...
```
But that size may or may not be suitable for the screen. Being able to find out whether it's a massive 3440x1440 screen or a tiny Raspberry Pi 320x200 screen would be really useful. Ideally, this information should be available before creating a window, to avoid having to create a default sized window (or a full screen context) only to then find out that it's not a good size and change the size when the window is already visible.

**Comment by 17cupsofcoffee** [comment]
Interesting! I hadn't really thought about that use case (I mainly make low resolution pixel art games so it hasn't really come up for me 😅).

I will have a think what sort of API could work here, and look at what other libraries do.

**Comment by 17cupsofcoffee** [comment]
The slightly tricky thing about this is that the `Context` is what initializes SDL2, which we need access to in order to get the info you want. So that would imply that we need a way to access the `Context` prior to window creation.

That would need to be done carefully though, because:

* I like how terse the code is to start a Tetra window at the minute, and I wouldn't want to make it much more complex.
* I don't want the API to give the false impression that Tetra supports multiple windows when it currently doesn't.
* We'd need to figure out how to handle passing a windowless context into a function like `graphics::clear(ctx)` - would it panic? No-op? Would this require massive changes under the hood?

I have been thinking about potential changes to the `Context` API recently, so I'll try to take this into account if/when I do a refactor.

EDIT: A less invasive solution might be to just not display the window until the game loop starts? This seems to be how [FNA handles it](https://github.com/FNA-XNA/FNA/blob/master/src/FNAPlatform/SDL2_FNAPlatform.cs#L946), and I tend to hold that up as the gold standard of SDL2-based game engines. I actually think Tetra did work like that at some point, dunno why I got rid of it...

**Comment by cralian** [comment]
As the saying goes, I completely agree that Tetra should "make the easy things easy", and starting a project with just a few lines is great. But the rest of the saying is "make hard things possible", so hopefully there will be a way to do it without hurting the easy stuff.

At the moment I cannot see a way to get display information, so maybe just having access to that could be useful? There is some stuff in [`tetra::graphics::GraphicsDeviceInfo`](https://docs.rs/tetra/0.3.5/tetra/graphics/struct.GraphicsDeviceInfo.html) but not current (and/or supported) resolution(s). If creating the actual window can be deferred until the mainloop starts (so you get a chance to have a look at the context before you return a `State`-implementing structure), that should be good enough to at least set the window size and determine which sprite set to use.

It's not an urgent request by any means... just an idea for the future.

**Comment by 17cupsofcoffee** [comment]
> As the saying goes, I completely agree that Tetra should "make the easy things easy", and starting a project with just a few lines is great. But the rest of the saying is "make hard things possible", so hopefully there will be a way to do it without hurting the easy stuff.

Yeah, this is exactly my thinking - I want to keep the easy project setup, but that doesn't mean that I don't want to support more low-level tweaking as well where it's needed.

> At the moment I cannot see a way to get display information, so maybe just having access to that could be useful? There is some stuff in tetra::graphics::GraphicsDeviceInfo but not current (and/or supported) resolution(s). If creating the actual window can be deferred until the mainloop starts (so you get a chance to have a look at the context before you return a State-implementing structure), that should be good enough to at least set the window size and determine which sprite set to use.

At the very least, I would like to add that at some point, seems like a nice thing to have! I would definitely like to support your use case fully, though.

**Comment by 17cupsofcoffee** [comment]
As a first step, I've deferred showing the window until the game loop begins. This means that you'll have all the way up until the [`init` closure in `run`](https://docs.rs/tetra/0.3.5/tetra/struct.Context.html#method.run) returns to inspect the window size and make as many tweaks to the context as you want. Should be released in 0.3.6.

I'd still like to investigate if there's a nicer API for this, but that'll likely be a breaking change, so it won't happen till 0.4.

**Comment by cralian** [comment]
Thanks for that, it sounds fine to me. I'm not sure how I can inspect the window size though (will that be an additional change, or is there some API I've missed?)

**Comment by 17cupsofcoffee** [comment]
[`window::get_size`](https://docs.rs/tetra/0.3.5/tetra/window/fn.get_size.html) and [`window::set_size`](https://docs.rs/tetra/0.3.5/tetra/window/fn.set_size.html) should hopefully do what you need? Same API you would use inside your main game code :)

**Comment by cralian** [comment]
Sorry, what I meant is "display resolution". The window size is either 1280x720 (default) or whatever is passed to `ContextBuilder::new()` so the code already knows what it is. But finding out the display resolution (or supported resolutions) is what this question was originally about.
I guess that modern games don't care about that - they just always use full-screen and then let the user set the resolution (and deal with the consequences). But it would be nice for a little desktop game that runs in a window to know what the current resolution is.

**Comment by 17cupsofcoffee** [comment]
Ooooh, sorry, yep - that's something else I need to add. Shouldn't be a breaking change, though - will work on it tonight.

**Comment by 17cupsofcoffee** [comment]
Done in https://github.com/17cupsofcoffee/tetra/commit/602abdc3bd52a171c2c0413065d3234b36eb507c!

New functions added:

* `get_monitor_count(ctx)`
* `get_monitor_name(ctx, monitor_index)`
* `get_monitor_width(ctx, monitor_index)`
* `get_monitor_height(ctx, monitor_index)`
* `get_monitor_size(ctx, monitor_index)`
* `get_current_monitor(ctx)`
* `get_current_monitor_name(ctx)`
* `get_current_monitor_width(ctx)`
* `get_current_monitor_height(ctx)`
* `get_current_monitor_size(ctx)`

The only thing that's missing is `set_current_monitor`, but that would require some upstream changes to the SDL2 crate.

Does that sound like it'll do what you need it to do? I'll probably release a new version with these changes over the weekend if so.

**Comment by cralian** [comment]
That's great! Thank you very much for the quick response and the new functionality.

**Comment by 17cupsofcoffee** [comment]
0.3.6 has been released 🎉
