### ISSUE TITLE
Error with static linking SDL2 Mac.

### ISSUE THREAD

**Issue by GRVYDEV** [17cupsofcoffee/tetra#193]
**Summary:**
Hi I am trying to statically link SDL2 in my build. I am currently getting this error "**could not find native static library `SDL2main`, perhaps an -L flag is missing?**" I know I have SDL2 installed however I am not sure what is causing this. Any suggestions would be great!

**Comment by 17cupsofcoffee** [comment]
Looking more closely at the docs for the SDL2 crate, it looks like it might need an extra feature flag enabling for things to link properly if you're not also using the `bundled` feature.

If you add this to your `[dependencies]` in `Cargo.toml` (making sure you're also using Tetra 0.4), does it work?

```toml
sdl2 = { version = "0.34.0", features = ["use-pkgconfig"] }
```

If so, that will work as a workaround until I figure out a better way of exposing that from Tetra properly.

If not, I'll have to investigate further...

**Comment by GRVYDEV** [comment]
That solved it! Thank you.

**Comment by GRVYDEV** [comment]
Alright I thought that solved it however now I am getting this error. 
```
Undefined symbols for architecture x86_64:
            "_OBJC_CLASS_$_MTLSamplerDescriptor", referenced from:
                objc-class-ref in libsdl2_sys-30c6c709f61685ba.rlib(SDL_render_metal.o)
            "_OBJC_CLASS_$_MTLTextureDescriptor", referenced from:
                objc-class-ref in libsdl2_sys-30c6c709f61685ba.rlib(SDL_render_metal.o)
            "_OBJC_CLASS_$_MTLRenderPassDescriptor", referenced from:
                objc-class-ref in libsdl2_sys-30c6c709f61685ba.rlib(SDL_render_metal.o)
            "_OBJC_CLASS_$_MTLVertexDescriptor", referenced from:
                objc-class-ref in libsdl2_sys-30c6c709f61685ba.rlib(SDL_render_metal.o)
            "_OBJC_CLASS_$_MTLRenderPipelineDescriptor", referenced from:
                objc-class-ref in libsdl2_sys-30c6c709f61685ba.rlib(SDL_render_metal.o)
            "_MTLCreateSystemDefaultDevice", referenced from:
                _METAL_CreateRenderer in libsdl2_sys-30c6c709f61685ba.rlib(SDL_render_metal.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I can run my game using cargo run with no problem.

**Comment by GRVYDEV** [comment]
I switched to using the bundled SDl2 and it works now.

**Comment by 17cupsofcoffee** [comment]
Glad you were able to fix it!

Looking at the error you got when you used `use-pkgconfig`, the missing symbols were all from Metal's API, so it might be that you needed to link that into your project as well. Presumably when you switched over to `bundled` it compiled SDL with Metal support disabled, or something like that.

I don't understand MacOS 😅
