### ISSUE TITLE
Provide a way of disabling unused texture/audio/font formats

### ISSUE THREAD

**Issue by 17cupsofcoffee** [17cupsofcoffee/tetra#196]
**Summary:**

There is currently no way to disable texture/audio/font formats that are not being used in a Tetra game. It would be a good idea to add some form of conditional compilation for these.

Some [very unscientific polling](https://twitter.com/17cupsofcoffee/status/1285255935464812544) on Twitter indicates that there's a few very common formats used, so we could maybe turn these on by default and make the rest opt in.

**Why is this needed?**

Having the decoders for unused formats in the dependency tree has two negative impacts:

* It increases clean compile times (which is a pain for people building their games on CI).
* It increases the number of crates that need license attribution providing alongside people's games.

**Comment by puppetmaster-** [comment]
Is it possible that tetra uses the [feature](https://github.com/image-rs/image/blob/3c3ccfded11d72cb02021539eea66ac2bea2989d/src/io/free_functions.rs) in the image crate?

**Comment by 17cupsofcoffee** [comment]
Yeah, that's the plan! The issue is that Cargo does not allow you to enable/disable features of indirect dependencies (i.e. there's no way for your project to disable features of `image` that `tetra` has already enabled). So I believe I would need to expose some features in Tetra's `Cargo.toml` that map to the features of `image` and `rodio` in order to get this working.

**Comment by 17cupsofcoffee** [comment]
Done in 786e1a8.
