### ISSUE TITLE
Expose runtime texture editing functionality

### ISSUE THREAD

**Issue by McGittyHub** [17cupsofcoffee/tetra#207]
**Summary:**
I need the ability to change parts of a texture for my game and tetra currently does not expose any way of accomplishing this. Thanks in advance.

**Comment by 17cupsofcoffee** [comment]
This functionality already exists in the [platform layer](https://github.com/17cupsofcoffee/tetra/blob/main/src/platform/device_gl.rs#L343) - I've been meaning to expose that through the public API for a while now. Mainly just needs some thought putting into error handling/making sure you can't write out of bounds.

**Comment by 17cupsofcoffee** [comment]
This has been added on the `main` branch and will be released in the next version.

**Comment by McGittyHub** [comment]
that is excellent news, thanks!

**Comment by 17cupsofcoffee** [comment]
0.5.1 is now released, sorry for the delay!
