### ISSUE TITLE
process didn't exit successfully : (exit code 0xc000007b)

### ISSUE THREAD

**Issue by Mechap** [17cupsofcoffee/tetra#208]
**Summary:**
When I cargo run the example shown in the website. I get this error.
![image](https://user-images.githubusercontent.com/54742369/97078590-69b78780-15ed-11eb-8418-251fe27527fa.png)

**Steps to reproduce:**
Make a new project with cargo init and add tetra in dependencies
![image](https://user-images.githubusercontent.com/54742369/97078571-4f7da980-15ed-11eb-9733-ef754b29b4da.png)

copy this code in main.rs
![image](https://user-images.githubusercontent.com/54742369/97078536-25c48280-15ed-11eb-99d7-3bf4e0bb6f0f.png)

execute cargo run

**Expected behavior:**
The code should run without any issues.

**Additional info:**
I'm on windows.

**Comment by Mechap** [comment]
In fact, I was using the x64 sdl2 dll instead of the x86 dll.

**Comment by 17cupsofcoffee** [comment]
That's an extremely confusing error message - I'll see if there's any way I can make this clearer so other people don't have the same issue :+1:
