### ISSUE TITLE
Camera zoom as Vec2

### ISSUE THREAD

**Issue by fossegutten** [17cupsofcoffee/tetra#222]
**Summary:**
Would like the zoom to be a Vec2<f32> instead of f32.

**Why is this needed?**
To do aspect ratio independent zooming. Useful to create a zoom value like this `zoom = desired_game_size / viewport_size`

**Comment by 17cupsofcoffee** [comment]
This wouldn't be too hard to do - the underlying matrix [already takes an X and Y parameter](https://github.com/17cupsofcoffee/tetra/blob/main/src/graphics/camera.rs#L109). It'd probably make sense to call it `scale` instead (for consistency with `DrawParams`) and change it to a `Vec2`. That would be a breaking change, though, so I'm not sure if there's a way I can do this until 0.6.

That said, `Camera` is deliberately designed to only use Tetra's public API - therefore, it's entirely possible for you to copy and paste it into your project and make modifications, if the current API doesn't suit your needs :) So hopefully that's an acceptable workaround for now.

**Comment by 17cupsofcoffee** [comment]
Done on the 0.6 branch.
