### ISSUE TITLE
Add Rectangle::union (or something like it)

### ISSUE THREAD

**Issue by 17cupsofcoffee** [17cupsofcoffee/tetra#242]
**Summary:**

There should be a method on `Rectangle` that gives you the union of two rectangles (i.e. a rectangle that surrounds them both).

The text caching functionality already does this to calculate the text's bounds, it just needs pulling out into a seperate method.

**Why is this needed?**

It's handy, and people have asked for it.

**Comment by BoxyUwU** [comment]
My first thought upon reading "union of two rectangles" was a rectangle that is the overlap of two rectangles x) I dont know if others would have that first thought (im probably totally wrong but i bring it up because it might be useful to know when writing docs)

**Comment by 17cupsofcoffee** [comment]
Yeah, I'm not sure about the naming either - I need to have a look at what other libraries call it :)

also `union` is a keyword lmao

**Comment by BoxyUwU** [comment]
r#union sounds like a great variable name

**Comment by 17cupsofcoffee** [comment]
Added `Rectangle::combine` on the `main` branch :)
