### ISSUE TITLE
FPS counter capped at 500

### ISSUE THREAD

**Issue by fossegutten** [17cupsofcoffee/tetra#263]
**Summary:**
FPS counter caps at 500. Not sure if the engine loop is capped or it is a bug in the Time struct. Please close if this is not a bug.

**Steps to reproduce:**
`time::get_fps(ctx) as i32)` caps at 500 when I draw as text. Disabled VSync, gsync and using Timestep::Variable

**Expected behavior:**
Expected the FPS to go higher, 

**Additional info:**

**Comment by 17cupsofcoffee** [comment]
This isn't a bug with the counter - I added a cap to the framerate as a short term fix for #213. The behaviour seems consistent with Love2D (which is where I took the idea for the 1ms sleep from) - I get exactly 500fps running that without vsync too.

So I think this is working as expected, but I'd definitely like to improve it - this is what #218 was raised for, so I'm going to close this as a duplicate of that. Thanks for reminding me to take another look at that, though!
