### ISSUE TITLE
Drawing many Text instances severely degrades performance on macOS

### ISSUE THREAD

**Issue by brettchalupa** [17cupsofcoffee/Tetra#347]
### Summary

I noticed that when I draw many `Text` instances frames start to drop. Calling `.draw` with more than 16 causes performance to degrade and the game to slow down.

**Note:** upon further research, this is only happening on macOS, and the slowness does not happen on Windows 11 or Linux Mint.

debug build results:

- 16 texts runs at a steady 120 FPS
- 17 texts causes frames to start dropping a little bit, ~117 FPS
- 40 texts halves the FPS to about 60 FPS
- 50 texts drops to about 40 FPS

I didn't notice any difference in performance when running `cargo run` (debug) or `cargo run --release` (release).

Happens with both the Vector (ttf) and Bitmap font from the example: https://github.com/17cupsofcoffee/tetra/blob/1d23de2c919f8b9106c9d703076935464079c8aa/examples/text.rs

<img width="1392" alt="Screenshot 2024-08-03 at 3 48 30 PM" src="https://github.com/user-attachments/assets/7822ee72-3a4b-4daf-9f94-770c68d023de">

I'm seeing a rock steady 60 FPS with **3,000** text instances drawn [with Macroquad](https://github.com/brettchalupa/macroquad_text_perf) when running `cargo run --release`.

### Steps to Reproduce

Project that can be run with Cargo: https://github.com/brettchalupa/tetra_text_perf

Relevant source example:

``` rust
use tetra::graphics::text::{Font, Text};
use tetra::graphics::{self, Color};
use tetra::math::Vec2;
use tetra::{Context, ContextBuilder, State};

const TEXT_OFFSET: Vec2<f32> = Vec2::new(16.0, 16.0);

struct GameState {
    texts: Vec<Text>,
}

impl GameState {
    fn new(ctx: &mut Context) -> tetra::Result<GameState> {
        let mut texts = vec![];
        for i in 1..51 {
            texts.push(Text::new(
                format!(
                    "{}: This is some text being rendered from a vector font.",
                    i
                ),
                Font::vector(ctx, "./DejaVuSansMono.ttf", 16.0)?,
                // NOTE: same behavior with a bitmap font as well
                // Font::bmfont(ctx, "./DejaVuSansMono.fnt")?,
            ));
        }

        Ok(GameState {
            texts,
        })
    }
}

impl State for GameState {
    fn update(&mut self, ctx: &mut Context) -> tetra::Result {
        tetra::window::set_title(
            ctx,
            &format!("Text Render Perf ({:.0} FPS)", tetra::time::get_fps(ctx)),
        );

        Ok(())
    }

    fn draw(&mut self, ctx: &mut Context) -> tetra::Result {
        graphics::clear(ctx, Color::rgb(0.392, 0.584, 0.929));

        for (i, text) in self.texts.iter_mut().enumerate() {
            let x = if i < 25 { 0.0 } else { 640.0 };
            let y = if i < 25 {
                (i as f32) * 18.0
            } else {
                ((i - 25) as f32) * 18.0
            };
            text.draw(ctx, TEXT_OFFSET + Vec2::new(x, y));
        }

        Ok(())
    }
}

fn main() -> tetra::Result {
    ContextBuilder::new("Rendering Text", 1280, 720)
        .quit_on_escape(true)
        .build()?
        .run(GameState::new)
}

```

### Additional Info

I'm on an Apple M2 Pro running on a MacBook Pro which normally runs my Tetra game at steadily at 120 FPS with sprite rendering.

I first noticed this when working on a dev tool for my game that renders text for scheduling actions to happen at a certain tick. The `T30`, etc. are all `Text` instances rendered with rotation:

<img width="1392" alt="image" src="https://github.com/user-attachments/assets/a70dfe3d-f5be-45e1-aff5-955fac8b0fc8">

Adding those Text draws dropped performance, so I thought I'd repro outside of my project and compare to Macroquad. I'm seeing ggez perform closely to Macroquad too when it comes to text rendering.

I'd be happy to try to fix this, but I could use a bit of direction and guidance on where to even start. Thank you so much for Tetra, I've been enjoying using it for the game project I'm working on and learning Rust.

**Comment by brettchalupa** [comment]
New info: I figured why not test this issue on Windows 11 to see if it's any different! Lo and behold, the `Text` drawing on Win 11 is very performant! On a AMD Ryzen 7 7840HS w/ Radeon 780M Graphics 3.80 GHz  with the power option set to Performance, I'm seeing a steady 60 FPS with **2,000 Text instances** using `cargo run --release`.

I adjusted the perf test as well so that it places the text positions randomly for making it easy to increase the number of them:

https://github.com/brettchalupa/tetra_text_perf/commit/5c48f5a42ecec1de2680c5ea948557b6a4214305

On Linux Mint on an Intel Core i7-5600U CPU @ 2.60 GHz x 2 with Intel HD Graphics 5500 (quite old X1 Carbon ThinkPad), I'm getting a steady 60 FPS with **1,500 Text instances**.

It seems safe to say this issue is just isolated to macOS.

**Comment by 17cupsofcoffee** [comment]
I haven't had chance to try the code example myself yet, but at first glance, I think the issue might actually be with how you're loading the fonts.

Some background: Tetra creates an underlying texture for each font you load, adding new glyphs to it whenever a piece of text asks for them. To draw a piece of text, Tetra just draws a load of slices of the font's texture, using it like a spritesheet.

However, in your example, you're loading the font multiple times, once for each of the texts - so they're all going to be using different textures, and the renderer is going to have to swap between them all whenever you draw your text. I'm pretty sure this is what's killing your performance.

The fix for this should be fairly simple - just load the font once (outside of the loop), and `clone` it for each text instead. Tetra's fonts are reference-counted objects, so if you clone them, the clone will point to the same underlying data (i.e. the same texture).

Possibly something that could be documented better! 

If you're still having performance issue even with that change, let me know.

**Comment by brettchalupa** [comment]
@17cupsofcoffee thank you so much for the support and explanation! I refactored the code based on your suggestion to this:


``` rust
let font = Font::vector(ctx, "./DejaVuSansMono.ttf", 16.0)?;
for i in 1..=4000 {
    texts.push((
        Text::new(
            format!("{}: This is some text.", i),
            font.clone(),
        ),
        x_between.sample(&mut rng) as f32,
        y_between.sample(&mut rng) as f32,
    ));
}
```

I'm getting a solid 60 FPS on my MacBook with **4,000 Text instance drawing** now.

Would you accept a PR that adds docs about this behavior? Happy to do so!

**Comment by 17cupsofcoffee** [comment]
Glad to hear this worked for you 😄

Yes, docs PRs are always welcome - there are already some performance notes on the Font type, but they don't currently cover this particular pitfall, so it would be great to add that!

I'm not entirely sure why it was only happening on Mac - possibly their OpenGL drivers/graphics cards are worse at handling lots of small draw calls?
