### ISSUE TITLE
Look at alternative ways of implementing the graphics backend

### ISSUE THREAD

**Issue by 17cupsofcoffee** [17cupsofcoffee/tetra#51]
Currently I'm using the `gl` crate and writing the unsafe wrapper myself, which scares me a bit...

Long term, we might want to move to something like `gfx-hal`, but we might be able clean things up a bit short-term by using the `gleam` wrapper library that Servo uses. It's basically just the code I've been having to write anyway, but much better tested and written by people who know what they're doing 😅 

EDIT: Okay I'm going to use this as a general purpose tracking issue for 'what do we use for getting pixels on the screen':

* `gleam` - Would probably be the simplest change, as it's basically as thin a GL wrapper as you can possibly write. This would probably be a nice short term step,
* `gfx-hal` - I like the idea of using this (and if I do, it'll probably be via contributing to whatever Icefoxen is working on) - that said, it doesn't currently look simple to get it working with SDL, and I'm categorically *not* dropping SDL until the Rust alternatives are more developed.
* `glium` - Probably the nicest/easiest to use GL wrapper, although I have some concerns about bugs/maintainance based on discussions I've seen on Discord.
* `luminance` - Looks quite 'Glium`-ish, might also be worth considering (especially as it seems a little less opinionated).

**Comment by 17cupsofcoffee** [comment]
I had a go at this on a seperate branch - it worked well for the most part! The main pain point would be that Gleam represents OpenGL as an `Rc` wrapped struct, which would require some rework on the `Drop` implementations for our GL handles. That said, I think that would go a long way towards resolving #1, so might be worth it...

Another alternative to this would be to just use `gl_generator` ourselves, but I don't know whether that would ramp up the build times.

**Comment by 17cupsofcoffee** [comment]
Another alternative would be [glow](https://github.com/grovesNL/glow) once that stabilizes more - it looks extremely cool, and could function as a pathway to getting Tetra running on the web/mobile?

**Comment by erlend-sh** [comment]
Amethyst will be using @omni-viral’s Rendy as an intermediate layer between the engine and gfx-hal. I believe ggez is headed down that same path. Might Tetra also standardize on Rendy?

https://github.com/omni-viral/rendy

**Comment by 17cupsofcoffee** [comment]
Quite possibly, although there was some (very early) talk of GGEZ having it's own 2D rendering crate, which would live at https://github.com/ggez/ggraphics. Whether that will be built on top of Rendy or gfx-hal directly, I'm not sure!

Either way, if that gets off the ground, that's probably the route I'd take for any potential gfx-hal rewrite - that way I could contribute to the ecosystem as a whole rather than just writing my own pile of janky rendering code :p

The main blocker for that for me is that I don't really want to move away from SDL until gil-rs is more developed - solid gamepad support is pretty important to me. I did have a look at the code for winit integration in gfx-hal though, and it doesn't seem *too* complicated, so maybe I'll have a go at porting that to use SDL? Obviously would only work for the Vulkan and GL backends, but still...

EDIT:

> it doesn't seem *too* complicated

Famous last words - I have no idea what I'm doing 😆

**Comment by erlend-sh** [comment]
Rendy is out now:
https://www.reddit.com/r/rust/comments/apeq8v/rendy_is_released/

gilrs is still being actively developed. Have you created issues for whatever is blocking you?

**Comment by 17cupsofcoffee** [comment]
I'd like to take more of a look at Rendy soon, but I feel like I'd need to learn Vulkan first, which is slightly intimidating 😅 

There's not one thing in particular blocking me (and I think any specific concerns I have already have issues raised)! I'm just not particularly in any rush to move away from SDL - it works, and it does everything I need right now.

That's generally the issue I have with the idea of switching to pure Rust dependencies - it'd add a lot more complexity (especially if I went for something gfx-hal based) without really giving me any tangible benefits, as far as I can tell.

**Comment by 17cupsofcoffee** [comment]
Now that [glow](https://github.com/grovesNL/glow) is reasonably stable (or at least stable enough that they're using it in gfx-hal's OpenGL backend), I'm pretty tempted to switch to that, at least as a first step.

**Comment by 17cupsofcoffee** [comment]
Closing this, as we've switched to glow for now. I'm working on a larger refactor of the graphics backend to make it a little more stateless/bindless, which should open the door to using other libraries eventually, but this is a good first step.
