### ISSUE TITLE
Audio thread crashes when playback ends on a detached instance of an MP3

### ISSUE THREAD

**Issue by 17cupsofcoffee** [17cupsofcoffee/tetra#85]
Reported by @puppetmaster- (as are a lot of these bugs :p) and replicated on my work laptop ~~- but not my main machine, which is strange...~~

The issue seems to get triggered under the following circumstances:

* The `Sound` has to have been created from an MP3.
* The `SoundInstance` has to have been dropped.
* Playback has just finished.
* **EDIT:** The sample rate of the sound doesn't match that of the output/sound card.
* **EDIT:** The project was built in debug mode (it's a debug only assertation that's triggering).

**Comment by 17cupsofcoffee** [comment]
Error message:  `thread 'rodio audio processing' panicked at 'assertion failed: self.next_frame.is_empty()', d:\Profiles\jclay\.cargo\registry\src\github.com-1ecc6299db9ec823\rodio-0.8.1\src\conversions\sample_rate.rs:186:13`

**Comment by 17cupsofcoffee** [comment]
Aha, just replicated on my desktop as well - it only happens if the sample rate of the sound doesn't match the sample rate of the output.

**Comment by 17cupsofcoffee** [comment]
The fix for #97 also seems to have resolved this 🎊

**Comment by puppetmaster-** [comment]
thx for fixing
